csnnades/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site_csnnades.urls')),
]

site_csnnades/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cadastrar_granada/<str:mapa_slug>/', views.cadastrar_granada, name='cadastrar_granada'),
    path('mirage', views.mirage, name='mirage'),
    path('nuke', views.nuke, name='nuke'),
    path('inferno', views.inferno, name='inferno'),
    path('ancient', views.ancient, name='ancient'),
    path('anubis', views.anubis, name='anubis'),
    path('overpass', views.overpass, name='overpass'),
    path('vertigo', views.vertigo, name='vertigo'),
    path('home', views.home, name='home'),
]

site_csnnades/models.py
from django.db import models
from embed_video.fields import EmbedVideoField

class Granada(models.Model):
    MAP_CHOICES = [
    ('Mirage', 'Mirage'),
    ('Inferno', 'Inferno'),
    ('Overpass', 'Overpass'),
    ('Nuke', 'Nuke'),
    ('Vertigo', 'Vertigo'),
    ('Anubis', 'Anubis'),
    ('Ancient', 'Ancient'),
    ]

    TIPO_CHOICES = [
        ('Smoke', 'Smoke'),
        ('Flash', 'Flash'),
        ('HE', 'High Explosive (HE)'),
        ('Molotov', 'Molotov'),
    ]

    BOMB_CHOICES = [
        ('Bomb A', 'Bomb A'),
        ('Bomb B', 'Bomb B'),
        ('Meio', 'Meio'),
    ]

    nome_mapa = models.CharField(max_length=50, choices=MAP_CHOICES)
    tipo_granada = models.CharField(max_length=20, choices=TIPO_CHOICES)
    bomb = models.CharField(max_length=30, choices=BOMB_CHOICES)
    link = EmbedVideoField(blank=True, null=True)
    descricao = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.tipo_granada} em {self.nome_mapa} para {self.get_bomb_display()}"

site_csnnades/forms.py
from django import forms
from .models import Granada

class GranadaForm(forms.ModelForm):
    class Meta:
        model = Granada
        fields = ['tipo_granada', 'bomb', 'link', 'descricao']

site_csnnades/views.py
from django.shortcuts import render, redirect
from .forms import GranadaForm
from .models import Granada
from django.contrib.auth.decorators import login_required


def cadastrar_granada(request, mapa_slug):
    if request.method == 'POST':
        form = GranadaForm(request.POST)
        if form.is_valid():
            granada = form.save(commit=False)
            granada.nome_mapa = mapa_slug
            granada.save()
            return redirect('home')
    else:
        form = GranadaForm()

    return render(request, 'cadastro_granada.html', {'form': form, 'mapa_slug': mapa_slug})

@login_required
def home(request):
    return render(request, 'home.html')

@login_required
def mirage(request):
    granadas = Granada.objects.filter(nome_mapa='Mirage')
    return render(request, 'mirage.html', {'granadas': granadas})

@login_required
def inferno(request):
    granadas = Granada.objects.filter(nome_mapa='Inferno')
    return render(request, 'inferno.html', {'granadas': granadas})

@login_required
def overpass(request):
    granadas = Granada.objects.filter(nome_mapa='Overpass')
    return render(request, 'overpass.html', {'granadas': granadas})

@login_required
def vertigo(request):
    granadas = Granada.objects.filter(nome_mapa='Vertigo')
    return render(request, 'vertigo.html', {'granadas': granadas})

@login_required
def anubis(request):
    granadas = Granada.objects.filter(nome_mapa='Anubis')
    return render(request, 'anubis.html', {'granadas': granadas})

@login_required
def nuke(request):
    granadas = Granada.objects.filter(nome_mapa='Nuke')
    return render(request, 'nuke.html', {'granadas': granadas})

@login_required
def ancient(request):
    granadas = Granada.objects.filter(nome_mapa='Ancient')
    return render(request, 'ancient.html', {'granadas': granadas})

site_csnnades/templates/ancient.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% block content %}

<body>

    <header>
        <h1>CSnNades - Ancient</h1>
        <a href="home">Voltar para a Página Inicial</a>
        <p>Explore estratégias, dicas e vídeos sobre o mapa Ancient no Counter-Strike.</p>
    </header>

    <main>

        <h2>Visão Geral</h2>
        <p>O mapa Ancient é conhecido por ser um mapa moderno e desafiador, com oportunidades ligeiramente favoráveis aos terroristas. É um mapa novo, lançado em 2022, e ainda está ganhando popularidade no cenário competitivo.</p>

        <a class="map-link" href="{% url 'cadastrar_granada' mapa_slug='Ancient' %}">
            <button class="custom-button">Adicionar Granada</button>
        </a>
        <h2>Smokes</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Smoke' %}
        <a href="{{ granada.link }}" class="video-link">{{ granada.descricao }}</a>
        <div class="video-container">
            {% video granada.link 'small' %}
        </div>

        {% endif %}
        {% endfor %}

        <h2>Flashbangs</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Flash' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

        <h2>Molotovs</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Molotov' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

        <h2>High Explosive (HE)</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'HE' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

    </main>

</body>
{% endblock %}

</html>

site_csnnades/templates/anubis.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% block content %}

<body>

    <header>
        <h1>CSnNades - Anubis</h1>
        <a href="home">Voltar para a Página Inicial</a>
        <p>Explore estratégias, dicas e vídeos sobre o mapa Anubis no Counter-Strike.</p>
    </header>

    <main>

        <h2>Visão Geral</h2>
        <p>O mapa Anubis é conhecido por ser um mapa moderno e acelerado, com oportunidades ligeiramente favoráveis aos contra-terroristas. É um mapa novo, lançado em 2023, e ainda está ganhando popularidade no cenário competitivo.</p>

        <a class="map-link" href="{% url 'cadastrar_granada' mapa_slug='Anubis' %}">
            <button class="custom-button">Adicionar Granada</button>
        </a>
        <h2>Smokes</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Smoke' %}
        <a href="{{ granada.link }}" class="video-link">{{ granada.descricao }}</a>
        <div class="video-container">
            {% video granada.link 'small' %}
        </div>

        {% endif %}
        {% endfor %}

        <h2>Flashbangs</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Flash' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

        <h2>Molotovs</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Molotov' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

        <h2>High Explosive (HE)</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'HE' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

    </main>

</body>
{% endblock %}

</html>

site_csnnades/templates/base.html
{% load embed_video_tags %}
<!DOCTYPE html>
<html lang="pt-br">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSnNades</title>
    <style>
        @font-face {
            font-family: 'speed';
            src: url(csnnades\site_csnnades\templates\fonts\HighSpeed.ttf) format('truetype');
            font-weight: normal;
            font-style: normal;
        }

        * {
            font-family: 'speed';
        }

        h1 {
            color: #4CAF50;
            margin: 0;
            font-size: 4.5em;
            text-align: center;
            margin-bottom: 20px;
        }

        body {
            background-color: #f8f8f8;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        header {
            text-align: center;
            background-color: #333;
            padding: 15px;
            color: #fff;
        }

        p {
            color: #555;
            font-size: 1.1em;
        }

        main {
            max-width: 700px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        a {
            color: #1E90FF;
            text-decoration: none;
            font-weight: bold;
            display: block;
            margin-bottom: 10px;
        }

        a:hover {
            color: #0D47A1;
        }

        main {
            /* Adicionando uma borda e espaçamento interno aos elementos de vídeo */
            border: 1px solid #ddd;
            padding: 10px;
            margin-bottom: 20px;
        }

        h2 {
            /* Adicionando um fundo sutil para destacar os títulos */
            background-color: #f2f2f2;
            padding: 8px;
            border-radius: 4px;
        }

        /* Estilo para os vídeos */
        .video-container {
            position: relative;
            width: 100%;
            padding-bottom: 56.25%;
            /* Proporção 16:9 para manter a consistência */
            overflow: hidden;
        }

        .video-container iframe,
        .video-container object,
        .video-container embed {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

        /* Estilo para os links */
        a.video-link {
            display: block;
            margin-top: 10px;
            color: #1E90FF;
            text-decoration: none;
            font-weight: bold;
            transition: color 0.3s ease;
            /* Transição suave da cor ao passar o mouse */
        }

        a.video-link:hover {
            color: #0D47A1;
        }

        .custom-button {
            display: inline-block;
            padding: 10px 15px;
            font-size: 16px;
            text-align: center;
            text-decoration: none;
            cursor: pointer;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #4CAF50;
            /* Cor de fundo do botão */
            color: white;
            /* Cor do texto do botão */
        }
    </style>

</head>
{% block content %}
{% endblock %}

</html>

site_csnnades/templates/cadastro_granada.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSnNades - Seu Portal de Granadas no Counter-Strike</title>    
    <style>
        @font-face {
            font-family: 'speed';
            src: url(csnnades\site_csnnades\templates\fonts\HighSpeed.ttf) format('truetype');
            font-weight: normal;
            font-style: normal;
        }
        *{
            font-family: 'speed';
        }
        h1 {
            color: #4CAF50;
            margin: 0;
            font-size: 4.5em;
            text-align: center;
            margin-bottom: 20px;
        }
        body {           
            background-color: #f8f8f8;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        header {
            text-align: center;
            background-color: #333;
            padding: 20px;
            color: #fff;
        }
        p {
            color: #555;
            font-size: 1.1em;
        }
        main {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #1E90FF;
            text-decoration: none;
            font-weight: bold;
            display: block;
            margin-bottom: 10px;
        }
        a:hover {
            color: #0D47A1;
        }
        main {
            /* Adicionando uma borda e espaçamento interno aos elementos de vídeo */
            border: 1px solid #ddd;
            padding: 10px;
            margin-bottom: 20px;
        }

        h2 {
            /* Adicionando um fundo sutil para destacar os títulos */
            background-color: #f2f2f2;
            padding: 8px;
            border-radius: 4px;
        }

        /* Estilo para os vídeos */
        .video-container {
            position: relative;
            width: 100%;
            padding-bottom: 56.25%; /* Proporção 16:9 para manter a consistência */
            overflow: hidden;
        }

        .video-container iframe, .video-container object, .video-container embed {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

        /* Estilo para os links */
        a.video-link {
            display: block;
            margin-top: 10px;
            color: #1E90FF;
            text-decoration: none;
            font-weight: bold;
            transition: color 0.3s ease; /* Transição suave da cor ao passar o mouse */
        }

        a.video-link:hover {
            color: #0D47A1;
        }
        form {
            max-width: 600px;
            margin: 0 auto;
        }

        h2 {
            color: #4CAF50;
            text-align: center;
            margin-bottom: 20px;
            font-size: 2.5em;
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
            color: #333;
        }

        input,
        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 1em;
        }

        button {
            background-color: #4CAF50;
            color: #fff;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1.2em;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<h2>Cadastrar Granada</h2>
<form method="post" action="{% url 'cadastrar_granada' mapa_slug=mapa_slug %}">
    {% csrf_token %}
    <label for="id_nome_mapa">Nome do Mapa:</label>
    {{ form.nome_mapa }}

    <label for="id_tipo_granada">Tipo de Granada:</label>
    {{ form.tipo_granada }}

    <label for="id_bomb">Localização da Bomba:</label>
    {{ form.bomb }}

    <label for="id_link">Link do Vídeo:</label>
    {{ form.link }}

    <label for="id_descricao">Descrição:</label>
    {{ form.descricao }}

    <button type="submit">Cadastrar Granada</button>
</form>

site_csnnades/templates/home.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSnNades - Seu Portal de Granadas no Counter-Strike 2</title>
    <style>
        @font-face {
            font-family: 'speed';
            src: url(csnnades\site_csnnades\templates\fonts\HighSpeed.ttf) format('truetype');
            font-weight: normal;
            font-style: normal;
        }

        * {
            font-family: 'speed';
        }

        h1 {
            color: #4CAF50;
            margin: 0;
            font-size: 4.5em;
            text-align: center;
            margin-bottom: 10px;
        }

        body {
            background-color: #f8f8f8;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        header {
            text-align: center;
            background-color: #333;
            padding: 20px;
            color: #fff;
        }

        p {
            color: #555;
            font-size: 1.1em;
        }

        main {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        a {
            color: #1E90FF;
            text-decoration: none;
            font-weight: bold;
            display: block;
            margin-bottom: 10px;
        }

        a:hover {
            color: #0D47A1;
        }

        .map-links {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }

        .map-link {
            position: relative;
            overflow: hidden;
            margin-bottom: 30px;
            margin-right: 30px;
        }

        .map-name {
            position: absolute;
            top: 0;
            left: 50%;
            transform: translateX(-50%);
            background-color: rgba(0, 0, 0, 0.7);
            color: #fff;
            width: 100%;
            text-align: center;
            padding: 8px 1;
            box-sizing: border-box;
            font-size: 1.0em;
        }

        .map-image {
            width: 100%;
            height: auto;
            max-width: 300px;
            /* Defina o tamanho máximo desejado */
            border-radius: 8px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        }
        .header-login {
            position: absolute;
            top: 20px;
            right: 20px;
            display: flex;
            align-items: center;
            }

            .header-login p {
            font-size: 0.8em;
            margin: 0;
            margin-right: 20px;
            color: #fff;
            }

            .header-login a {
            padding: 5px 10px;
            border: 1px solid #fff;
            border-radius: 4px;
            }

            .header-login a:hover {
            background-color: #fff;
            color: #333;
            }

    </style>

</head>

<body>

    <header>
        <h1 href="{% url 'home' %}">CSnNades</h1>
        <p>Seu Portal de Granadas no Counter-Strike 2</p>
        <div class="header-login">
          <p>{{ request.user.username }} logado(a)!</p>
          {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
          {% endif %}
        </div>
      </header>

    <main>
        <div class="map-links">
            <a class="map-link" href="{% url 'mirage' %}">
                <div class="map-name">Mirage</div>
                <img class="map-image" src="https://media.moddb.com/images/downloads/1/249/248576/A.png" alt="Mirage">
            </a>
            <a class="map-link" href="{% url 'inferno' %}">
                <div class="map-name">Inferno</div>
                <img class="map-image"
                    src="https://img-cdn.hltv.org/gallerypicture/nnyGiC9yrs0v1-8xLbMluN.jpg?ixlib=java-2.1.0&w=1200&s=63b0dc0448c5128770b3b1586abe98d3"
                    alt="Inferno">
            </a>
            <a class="map-link" href="{% url 'overpass' %}">
                <div class="map-name">Overpass</div>
                <img class="map-image" src="https://static.draft5.gg/news/2023/07/18090850/Overpass-Bombsite-B-CS2.jpg"
                    alt="Overpass">
            </a>
            <a class="map-link" href="{% url 'nuke' %}">
                <div class="map-name">Nuke</div>
                <img class="map-image" src="https://escorenews.com/media/news/pic-20230630-1536x864-2159679631.png"
                    alt="Nuke">
            </a>
            <a class="map-link" href="{% url 'vertigo' %}">
                <div class="map-name">Vertigo</div>
                <img class="map-image"
                    src="https://img-cdn.hltv.org/gallerypicture/QBFVAZo3nFFwbt3sodMgIS.png?ixlib=java-2.1.0&w=1200&s=9f0d6d8b343ce00f5307aebb9b2c8c3c"
                    alt="Vertigo">
            </a>
            <a class="map-link" href="{% url 'anubis' %}">
                <div class="map-name">Anubis</div>
                <img class="map-image"
                    src="https://s2-ge.glbimg.com/gEATSZslQ_rX--ziWT_NfK0UGLU=/0x0:1920x1080/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_bc8228b6673f488aa253bbcb03c80ec5/internal_photos/bs/2023/2/u/PSygwxQWCWYVWBb6hJfw/bomb-a-ancient-cs2.png"
                    alt="Anubis">
            </a>
            <a class="map-link" href="{% url 'ancient' %}">
                <div class="map-name">Ancient</div>
                <img class="map-image"
                    src="https://s2-ge.glbimg.com/2uOPA8XzFmH41MjSNkBBPNjaceo=/0x0:1920x1080/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_bc8228b6673f488aa253bbcb03c80ec5/internal_photos/bs/2023/A/J/lNTTNASBSgBbhcfUp9FA/ancient-cs2-1.png"
                    alt="Ancient">
            </a>
        </div>
    </main>

</body>

</html>

site_csnnades/templates/inferno.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% block content %}

<body>

    <header>
        <h1>CSnNades - Inferno</h1>
        <a href="home">Voltar para a Página Inicial</a>
        <p>Explore estratégias, dicas e vídeos sobre o mapa Inferno no Counter-Strike.</p>
    </header>

    <main>

        <h2>Visão Geral</h2>
        <p>O Inferno é um mapa conhecido por suas ruas estreitas e pontos-chave de controle. Entenda as dinâmicas deste
            mapa e aprimore suas habilidades táticas.</p>

        <a class="map-link" href="{% url 'cadastrar_granada' mapa_slug='Inferno' %}">
            <button class="custom-button">Adicionar Granada</button>
        </a>
        <h2>Smokes</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Smoke' %}
        <a href="{{ granada.link }}" class="video-link">{{ granada.descricao }}</a>
        <div class="video-container">
            {% video granada.link 'small' %}
        </div>

        {% endif %}
        {% endfor %}

        <h2>Flashbangs</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Flash' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

        <h2>Molotovs</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Molotov' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

        <h2>High Explosive (HE)</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'HE' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

    </main>

</body>
{% endblock %}

</html>

site_csnnades/templates/mirage.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% block content %}

<body>

    <header>
        <h1>CSnNades - Mirage</h1>
        <a href="home">Voltar para a Página Inicial</a>
        <p>Explore estratégias, dicas e vídeos sobre o mapa Mirage no Counter-Strike.</p>
    </header>

    <main>

        <h2>Visão Geral</h2>
        <p>
            O mapa Mirage é conhecido por ser um mapa equilibrado, com oportunidades iguais para terroristas e contra-terroristas. É um mapa popular no cenário competitivo, e é frequentemente usado em torneios.</p>

        <a class="map-link" href="{% url 'cadastrar_granada' mapa_slug='Mirage' %}">
            <button class="custom-button">Adicionar Granada</button>
        </a>
        <h2>Smokes</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Smoke' %}
        <a href="{{ granada.link }}" class="video-link">{{ granada.descricao }}</a>
        <div class="video-container">
            {% video granada.link 'small' %}
        </div>

        {% endif %}
        {% endfor %}

        <h2>Flashbangs</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Flash' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

        <h2>Molotovs</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Molotov' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

        <h2>High Explosive (HE)</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'HE' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

    </main>

</body>
{% endblock %}

</html>

site_csnnades/templates/nuke.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% block content %}

<body>

    <header>
        <h1>CSnNades - Nuke</h1>
        <a href="home">Voltar para a Página Inicial</a>
        <p>Explore estratégias, dicas e vídeos sobre o mapa Nuke no Counter-Strike.</p>
    </header>

    <main>

        <h2>Visão Geral</h2>
        <p>O mapa Nuke é conhecido por ser um mapa perigoso e tático, com oportunidades ligeiramente favoráveis aos contra-terroristas. </p>

        <a class="map-link" href="{% url 'cadastrar_granada' mapa_slug='Nuke' %}">
            <button class="custom-button">Adicionar Granada</button>
        </a>
        <h2>Smokes</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Smoke' %}
        <a href="{{ granada.link }}" class="video-link">{{ granada.descricao }}</a>
        <div class="video-container">
            {% video granada.link 'small' %}
        </div>

        {% endif %}
        {% endfor %}

        <h2>Flashbangs</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Flash' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

        <h2>Molotovs</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'Molotov' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

        <h2>High Explosive (HE)</h2>
        {% for granada in granadas %}
        {% if granada.tipo_granada == 'HE' %}
        {% video granada.link 'small' %}
        <a href="{{ granada.link }}">{{ granada.descricao }}</a>
        {% endif %}
        {% endfor %}

    </main>

</body>
{% endblock %}

</html>